### ISSUE TITLE
Add frontend parameter for passing in country code

### ISSUE THREAD

**Issue by andrewmarriott-aws** [aws-solutions/amazon-marketing-cloud-uploader-from-aws#76]
https://github.com/orgs/aws-solutions/projects/9/views/5?pane=issue&itemId=19369017

**Comment by ianwow** [comment]
Here are some of the tasks associated with this issue:

- Add country code dropdown to the webform in Step 2, Define Dataset. Use 'US' as default.
- Persist that value to vuex so it's the same when users navigate away and come back to Step 2
- Update the API country code is included in POST /start_amc_transformation. Return an error if it is not included.
- Update args to glue job so you can pass country code in
- Parse country code in glue job as a required parameter. Return an error if it is not present.
- Update integration test so it does not fail. (It will probably fail since you changed the API)
- Update selenium test so it does not fail. (It will probably fail since you changed the API)
- Update the README and IG with screenshots and description of what the country code does.

**Comment by andrewmarriott-aws** [comment]
Finished #83
